spring.application.name=JpaHibernative
spring.datasource.url=jdbc:postgresql://localhost/JpaHibernative
spring.datasource.username=postgres
spring.datasource.password=3323
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update